on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0,4,8,12,16,20 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: apt-get update
        run: sudo apt-get update
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21.3' # The Go version to download (if necessary) and use.
      - name: Install lix
        run: npm i lix -g
      - name: Run lix
        run: npx lix download
      - name: Build samples
        run: npx haxe samples.hxml
      - name: Build
        run: npx haxe build.hxml
      - name: Build graph data
        run: npx haxe build_data.hxml
      - name: Build graph
        run: npx haxe graph.hxml
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'page'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - uses: EndBug/add-and-commit@v9
        with:
            message: update graph data
            add: ./test883/results.json
            pull: --rebase --autostash
